### ISSUE TITLE
Tutorial.md vs. Wiki

### ISSUE THREAD

**Issue by alex-strobel** [alex-strobel/NFC-Family#3]
Hi Josephine, 

I wrote a file Tutorials.md (see Misc/Workflows), but just wondered whether these contents should better be placed in the Wiki. What do you think? I guess, we will not have much to enter in the Wiki, so it may be ok to have this Tutorials.md file that might easier to be found when directly accessible via the main folder structure ...

Best,
A.

**Comment by JZerna** [comment]
It is absolutely okay to leave the Wiki empty, but if you prefer adding the tutorial links there for easy access, sure, why not?
